#!/bin/sh
export LANG='en_US.UTF-8'
java -Dloader.path='.' \
     -Dspring.config.location=application.yml \
#     -Dcom.sun.management.jmxremote \
#     -Dcom.sun.management.jmxremote.port=9010 \
#     -Dcom.sun.management.jmxremote.rmi.port=9010 \
#     -Dcom.sun.management.jmxremote.authenticate=false \
#     -Dcom.sun.management.jmxremote.ssl=false \
#     -Djava.rmi.server.hostname=81.23.10.106 \
     -jar ./sql-boot.jar